services:
  db:
    image: mysql:8.0
    container_name: app-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-symfony_db}
      MYSQL_USER: ${MYSQL_USER:-symfony_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-symfony_pass}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-changeme}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - traefik-network

volumes:
  db-data:
